include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    public_member_api_docs: ignore
